

package io.github.kyay10.regional.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.kyay10.regional.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  @Test
  @TestMetadata("ad.kt")
  public void testAd() {
    runTest("compiler-plugin/testData/diagnostics/ad.kt");
  }

  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("file.kt")
  public void testFile() {
    runTest("compiler-plugin/testData/diagnostics/file.kt");
  }

  @Test
  @TestMetadata("handlesLambdaParameters.kt")
  public void testHandlesLambdaParameters() {
    runTest("compiler-plugin/testData/diagnostics/handlesLambdaParameters.kt");
  }

  @Test
  @TestMetadata("inline.kt")
  public void testInline() {
    runTest("compiler-plugin/testData/diagnostics/inline.kt");
  }

  @Test
  @TestMetadata("revState.kt")
  public void testRevState() {
    runTest("compiler-plugin/testData/diagnostics/revState.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    runTest("compiler-plugin/testData/diagnostics/simple.kt");
  }

  @Test
  @TestMetadata("smartCasted.kt")
  public void testSmartCasted() {
    runTest("compiler-plugin/testData/diagnostics/smartCasted.kt");
  }

  @Test
  @TestMetadata("typealias.kt")
  public void testTypealias() {
    runTest("compiler-plugin/testData/diagnostics/typealias.kt");
  }
}
